### ISSUE TITLE
Sweet spot Office - Geospatial data project

### ISSUE THREAD

**Issue by maria-luisa-gomez** [Ironhack-Data-Madrid-Agosto-2021/W4-geospatial-data-project#1]
https://github.com/maria-luisa-gomez/sweet-spot-office

**Comment by AnaAGG** [comment]
# Proyecto geoqueries

Hola hola Maria Luisa 🙋🏻‍♀️, vamos con el tercer proyectooo

## README

En general trabajazo con el readme, solo como detalle:

- Me encanta la parte de los `steps` pero pondría un poco menos de texto para facilitar la lectura, por el resto 🔝 


## Estructura del repo

Wow Maria Luisa, trabajo perfecto en relación a la organización del repo 🔝, no tengo nada que decirte 🎉

## Sintaxis de código

Vamos con el código, como siempre vamos fichero por fichero: 

- **1 - MongoQueries_CompaniesCollection_find_city**

    Muy buen trabajo en este jupyter Maria Luisa, has ido desgranando el problema poco a poco, enfrentando los problemas step by step y tomando decisiones en función de los resultados que ibamos obteniendo.

    Muy buen flujo de trabajo para tomar la decisión del lugar donde queremos poner nuestra empresa

- **2 - Foursquare API**

  - Suuper bien que tengas los *docstrings* en las funciones. Vamos a darle una vueltita a como hacerlos para que queden perfectitos. ¿Qué tenemos que poner?
    - Qué es lo que hace la función en una linea
    - Qué argumentos (*Args*) recibe la función y de que tipo son
    - Qué nos devuelve (*Returns*) la función
    
      Poniendo como ejemplo una de tus funciones: 

      ```python
      def getCoordinates(direcciones):

      '''
      Given a list of addresses/name of locations it gives you back a dictionary with the latitute and longitude of each of them. 

      Args: 
          Direcciones (list): list of addresses/location names

      Returns: 
          A dictionary with their correspodant coordinates
      '''
      dict_ = {}
      try: 
          for direccion in direcciones:
              locations = requests.get(f'https://geocode.xyz/{direccion}?json=1')
              locations = locations.json()
              dict_[direccion] = locations
      except:
          return "Error"
          
      return dict_
      ```
  - Te has dejado los tokens Maria Luisaaaaa. De todas formas vemos eso que me decías para entender por que no te estaba pillando los tokens. 

  - Voy a ponerme un poco tiquismiquis, tu función de llamada a la API de foursquare está perfecta, luego haces las llamadas por separado a la función para cada ciudad. Pero... imaginate que quieres hacerlo para 10 ciudades, sería un poco tedioso. 

      Lo que podríamos hacer en este caso es usar un *for loop* donde llamaremos a la función

      ```python
      # creamos una lista o diccionario como tienes tu con las coordenadas de las ciudades que nos interesan
      coordinates = {'160 Spear St San Francisco USA': [-122.39312, 37.79179], '3 Park Avenue New York USA': [-73.98037, 40.69651]}
      for k,v in coordinates.items():
          af.foursquareQueries(v[1],v[0], url, *queries)
      ```
  - Vamos con esta función `responseGroups`, entiendo que la haces porque tienes un diccionario con todas las respuestas de la llamada de la API, pero... en realidad no sería necesaria teniendo las dos siguientes funciones `getFromDict` y `toDataFrame`. Me podrías explicar (contestando a la pull request que te envio) el por qué haces la función y explicandome un poco el código? 
  - En la parte final del jupyter, si todo el código que tienes para sacar la categoria lo metes en una función quedaría perfectito, porque si te fijas estas repitiendo el código varias veces y eso que solo tienes ciudades 😉

- **3 - Near Geoqueries**

Suuper buen trabajo de nuevo en este jupyter Maria Luisa. Solo un detalle:

- La función `nearQueries` esta genial, pero al final es una función muy grande que podriamos dividir en dos. 
  - La primera que cree la base de datos y la colección

    ```python
    def create_bbdd (gdf, mongo_database, collection_name):

        client = MongoClient(f"mongodb://localhost/{mongo_database}")
        db = client.get_database()
        col = db[f"{collection_name}"]

        if col.drop():
            print('Collection already exists -> Collection Deleted')
        else:
            print('This collection is new -> Collection Created')

        collection = db.create_collection(name = f"{collection_name}")
        collection.create_index([("geometry", GEOSPHERE)])

        data = gdf.to_dict(orient='records')
        collection.insert_many(data)
        return "collection cretated"
        ```
  - La segunda que haga la geoquery

    ```python
    def nearQueries (lon, lat, max_distance, collection)
        query = [{
        "$geoNear": {'near': [lon, lat],
                    'distanceField': 'distance',
                    'maxDistance': max_distance,
                    'distanceMultiplier': 6371, 
                    'spherical'  : True}}]
        geoloc = collection.aggregate(query)
        # response_json = json.loads(dumps(geoloc))
        
        return list(geoloc)
    ```
- **4 - Compare cities**

    - En la función `categoryAggr` tienes 18 linead de código que basicamente hacen lo mismo pero con distintos patrones! Ejercicio de paciencia que hiciste en esta función. Recuerda que cuando vemos que tenemos muchas lineas de código similares es el momento de empezar a atommizar el código. 

    ¿Qué podemos hacer en este caso? 

    Podemos crearnos un dicionario donde las *keys* sea por lo que queremos reemplazar y los values el patrón de regex y podemos usar el metodo `search` 

    ```python
     diccionario = {
          "Transportation" : re.search(r".*?Airport.*\w? | .*?Car.*\w? | .*?Taxi.*\w?", str(col)), # acuerdate del operador `|` que nos permite poner varias condiciones en regex
          "Pet Services" : re.search(r'.*?Pet.*\w?', str(col))

          # y así para todas los patrones que quieras buscar

          } 
    for k,v in diccionario.items():
        # si encuentra un value en el diccionario me devuelves la key del diccionario
        if v == True:
            return k
        else:
            # si no me devuelves otra cosa
            return "other"
    ```
    - Algo similar puedes hacer para la función `importance` 😉
  
## TODOs

Bueno en general muy buen trabajo Maria Luisa, te dejo por aquí un pequeño resumen con las cosas importantes 

- Atomizar un poco más el código en algunas partes, sobre todo al final. 
- Explicarme la función `responseGroups`, por qué y para qué la has hecho. 
- Darle a los diccionarios dentro de algunas funciones


Buen trabajo Maria Luisaaa 💪🔥


![image](https://user-images.githubusercontent.com/75084991/132657326-f9a264c6-e463-4144-9781-229102b143a6.png)
