### ISSUE TITLE
Nowhere

### ISSUE THREAD

**Issue by jalex141** [Ironhack-Data-Madrid-Agosto-2021/W4-geospatial-data-project#2]
https://github.com/jalex141/Nowhere.git
Alejandro

**Comment by AnaAGG** [comment]
# Proyecto geoqueries

Hola hola Alejandrooo 🙋🏻‍♀️, vamos con el tercer proyectooo

## README

Alejandro que pasó con el readme?? Tienes un readme pero es del repo que compartimos con vosotros, te tienes que crear tu uno ajustado a tu proyecto. 

El readme es condición indispensable para la entrega del proyecto 😔. 

## Estructura del repo

En cuanto a la organización del repo esta super bien y muy clara y lo más importante, no se te ha pasado ningún archivo temporal ni nada que no quieras enseñar fuera del `.gitignore` 👏🏽

Como detalles de cara al futuro:

- En la carpeta `src` tienes un archivo `.py` lo cual está genial. Solo como detalle, llamas al fichero `functions.py`. Tenemos que evitar ponerle esos nombres tan genéricos a los archivos, es mejor ponerle nombres que nos indiquen que es lo que nos vamos a encontrar dentro. 

    Por ejemplo, si dentro tienes funciones que vas a usar en la llamada a la API lo puedes llamar `API_functions`. 

    Podemos crearnos tantos archivos `.py` como queramos. De esta forma, si tenemos 2 procesos en nuestro proyecto (por ejemplo API y geoqueries) nos podemos crear dos `.py` independientes:

    - API_functions.py: donde tendremos las funciones de la llamada a la API
    - Geoqeuries_functions.py: donde tendremos las funciones de las geoqueries. 
- En los dosjupyters que presentas, tienes basicamente la misma información. Evitar tener jupyters con la misma info que puedan resultar confusos. 


🔴 Si se crea algun csv o un json decirle que lo guarde por si hay problemas con la api. En ese caso, se puede crear una carpeta de data

🔴Distintos jupyter, uno para cada parte del proyecto

## Sintaxis de código

Vamos con la parte del código de tu proyecto

- En las funciones acuerdate de los docstrings!! Son super importantes para entender que hacen tus funciones cuando estes trabajando en equipo. 

    ¿Cómo hacemos un buen *docstring*? 

    Tomando como ejemplo una función tuya

    ```python
    def clean(list_):

        '''
        Esta función limpia una lista para eliminar aquellos registros que no tienen valores

        Args: 
            list_ (lista): lista con los resultados de una query a la colección de mongo
        Returns:
            la misma lista pero limpia, eliminando aquellos registros que son nulos para determinads carácteristicas
        '''
    for n,seed in enumerate(list_):
        for i,office in enumerate(seed["offices"]):
            if office["latitude"] == None:
                del seed["offices"][i:]
            if len(seed["offices"])==0:
                del list_[n]
    return list_
    ```

    Por lo tanto, tenemos que poner, lo que hace, lo que recibe (Args) y los que nos devuelve (returns)
## TODOs

- Quedo la parte de las geoqueries pendiente, si quieres algun día nos sentamos y lo vemos juntos 😉
- El readmeeee
- Mejorar la estructura del repo

Bueno Alejandro, quedaron algunas pendientes, pero como te dije si quieres lo miramos juntos!! Seguimossssss

![image](https://user-images.githubusercontent.com/75084991/133001047-bb9eef42-22bd-4030-9229-91487c6e6e50.png)
