### ISSUE TITLE
Where should I put my office? (Jorge Solana)

### ISSUE THREAD

**Issue by Jorge-Solana** [Ironhack-Data-Madrid-Agosto-2021/W4-geospatial-data-project#3]
https://github.com/Jorge-Solana/GeoProject

**Comment by AnaAGG** [comment]
# Proyecto geoqueries

Hola hola Jorge 🙋🏻‍♀️, vamos con el tercer proyectooo

Ui ui, creo que es la primera pull request/issue que no me dejas un comentario!!!!

## README

Let's go con el readme! En general esta parte del proyecto esta perfectita, pero ya sabes que siempre tengo algún detallin que dar: 

- En la parte de metodología, tal vez lo podrías hacer un poco más esquemático, como *bullet points*. Por ejemplo en el primer punto tienes esto 

    ```
     Tener una startup grande cerca, tener restaurantes veganos cerca (ya que el CEO es vegano, este criterio tiene mucho peso), tener Starbucks cerca, que haya algún veterinario cerca (ya que el perro Dobby es muy querido por todos los integrnates de la empresa) y por último la proximidad a un bar.
    ```
    En vez de ponerlo todo junto lo puedes poner como una lista
- En este repo ya tenemos más archivos y `.py` mi recomendación, que es algo más personal es que tengas un apartado con la estructura de tu repositorio. Lo que podemos encontrar en cada carpeta y archivo (pero de una forma muy esquemática y explicado con pocas palabras, no más de una línea)
  
## Estructura del repositorio


Vamos con la estructura que ya va cogiendo forma! 

- Tienes varios ficheros `csv`, mételos en una carpeta que se llame por ejemplo `data` para que queden todos bien agrupaditos


- Tienes una carpeta que se llama `.ipynb_checkpoints` donde tienes algunos jupyters, pero también tienes un jupyter fuera. Aquí tres detalles: 
  - Intenta poner todos los jupyters en la misma carpeta

  - Intenta no llamar a esta carpeta con los checkpoints, esa es la carpeta que se genera como copia de seguridad y no se suele ni mirar. 
  
  - Si ya numeras los jupyters dentro de la carpeta te quedaría 🔝 de organización.

- El `.env` mételo en el `.gitignore`

- El `gitignore` fuera de la carpeta de los jupyters

En general esta bien, pero tengo que decirte que me ha costado un poco seguir el orden de trabajo de este proyecto 😔

## Sintaxis de código

Lo primerito de todo, enhorabuena por hacer un `.py` con la parte de la llamada a la API de foursquare 💪

- **main**
  - Sobre el nombre de las funciones, se que te lo podría haber dicho antes pero siempre se me olvida... Intenta poner nombres más indicativos de lo que hace la función, mas intuitivos. Por ejemplo las funciones `todo` o `funcionquefunciona`
  - Por ponerme tiquismiquis, en este fichero, importas los `csv` que generas de la llamada a la API, pero date cuenta que no te hace falta porque los tienes creados en en los *for* anteriores.
  - Como detalle, en el `.py` podemos tener un problema si lo ejecutamos varias veces el archivo con la creación de la colección. Nos dará un error por que la base de datos ya está creada. 

    ¿Que es lo que podemos hacer?

    Usar el método `drop` de mongo

    ```python
    db.collection.drop()
    # si pones esto antes de la creación de la colección nos ahorraremos errores en el futurooo
    ```
  - Por el resto todo perfectito 💪💪
- **MongoCosas**

    Suuper bien este juypter Jorge, super documentadito y con un buen *story telling* como siempre 😉

    Solo me ha faltado una cosita para rematar el proyecto, un mapita 🗺. Pero bueno queda entre los TODOs

## TODOs

Venga, como siempre un pequeño recap de las cosas que quedan un poco más pendientes en este proyecto

- Sintetizar un poco el readme
- Darle un poco más de orden al repo
  - Carpetas con los datos
  - Mover `.gitignore` y `.env`
  - Evitar usar `.ipynb_checkpoints`
- Cambiar los nombres de las funciones
- Un mapita para cerrar el proyecto

Bueno Jorge, no ha sido para tanto, hiciste muy buen proyecto aunque no lo creas 😉. En este lab hemos aprendido APIs, meter datos en mongo y hacer geoqueries 🚀

![image](https://user-images.githubusercontent.com/75084991/132705621-4bc3b723-6230-4868-b261-1b66b382be29.png)
