### ISSUE TITLE
https://github.com/DiegoCefalo/company_location

### ISSUE THREAD

**Issue by DiegoCefalo** [Ironhack-Data-Madrid-Agosto-2021/W4-geospatial-data-project#4]
https://github.com/DiegoCefalo/company_location

**Comment by AnaAGG** [comment]
# Proyecto geoqueries 

Hola hola Diego 🙋🏻‍♀️, vamos con el tercer proyectooo

## README

En general esta bastante bien el readme, pero yo lo haría un poco más esquemático para facilitar su lectura. Te dejo por aquí unos cuantos detallines más: 

- Igual que pones el link a la documentación de las librerias, puedes poner el link que lleva a la documentación de la API de foursquare. 

- Puedes explicar por que has elegido esas ciudades. 

- También puedes explicar un poco mejor cual es tu método de ponderación.

Como te digo, son detalles, en general buen trabajo Diego! 

## Estructura del repo

Vamos con la estructura del repo Diego! 

- Si tienes un jupyter que no quieres que la gente no vea `desastre(no ver)` no lo dejes en el repo. Para eso tenemos el `.gitignore` para meter aquellos ficheros que no queremos que se vean de nuestro proyecto.

- Tienes tres carpetas (LA, Londres y Madrid) en todas tienes sus json. En vez de tener tres carpetas, crea una única que se llame `data` por ejemplo y donde metas esas tres carpetas

- Intenta no llamar al archivo `.py` "funcioncitas" ni "funciones"... que tenga un nombre más descriptivo, que se sepa solo con leer el título que nos vamos a encontrar

- En este proyecto solo tienes un jupyter, pero puede ser que más adelante acabes trabajando con más jupyters. En este caso, lo ideal sería que te hicieras otra carpeta donde los guardes todos. Si además los numeras para saber cual es el orden de trabajo que quedaría perfectoooo

Aún con las cosinas que te dije, en general tienes muy buen trabajo Diegoooo

## Sintasis de código

- Muy bien documentado el jupyter Diego 😉!
- Voy a ponerme un poco tiquismiquis con algunas funciones: 
  - Función `foursq`, como la tienes esta perfect, pero podríamos hacerla un poco más general. Por ejemplo:
    - Tienes los tokens dentro de la función lo que haría que yo no podría usar tu función, por lo tanto, los puedes pasar como parámetros. 
    - Lo mismo para la url, la puedes pasar como un parámetro por si otro usuario quiere hacer las llamadas a otro `endpoint` de la API. 
  
    Por lo tanto, la función nos quedaría algo como esto: 

    ```python
    load_dotenv()
    client_id = os.getenv("token1")
    client_secret = os.getenv("token2")
    url_query = 'https://api.foursquare.com/v2/venues/explore'

    def foursq(venue,coords, client_id,client_secret, url_quer ):
      
        parametros = {
            "client_id": client_id,
            "client_secret": client_secret,
            "v": "20180323",
            "ll": f"{coords[0]}, {coords[1]}",
            "query": f"{venue}",
            "limit": 200,
            "radius": 10000
            }
        resp = requests.get(url_query, params = parametros).json()
        return resp
    ```
  - Función `mapamatico`: 
  
    Tienes estructuras de código en esta función que se repiten múltiples veces 

    ```python
    vegano = datamatico("Vegan restaurant",coords)
    starbucks = datamatico("Starbucks",coords)
    guarderia = datamatico("Daycare",coords)
    basketball = datamatico("Basketball arena",coords)
    bar = datamatico("Bar",coords)

    # para evitar esto lo que puedes hacer es crearte un diccionario primero y luego iterar por el e ir introduciendo los valores dl diccionario en la función `datamatico`
    ```

Por el resto todo perfecto! Como detalle, evitar usar esos nombres en la funciones en un entorno más laboral, bueno esto yo creo que te lo dijo Sheriff en la presentación 😉

## TODOs
Bueno Diego, suuper trabajo en este proyecto, te dejo por aquí un resumen de los puntos que podrías tocar en el futuro

- Atomizar un poco más alguna de las funciones
- El readme darle un poco más de estructura
- Reorganizar un poco el repo, sobre todo en la parte de los datos. 


Con todo, muy buen trabajo Diegooo 💪🔥

![image](https://user-images.githubusercontent.com/75084991/133000722-33fd322e-8754-41bd-8083-57858e9e9a51.png)
