### ISSUE TITLE
We are moving our office to a better place

### ISSUE THREAD

**Issue by diegodiazgarciadev** [Ironhack-Data-Madrid-Agosto-2021/W4-geospatial-data-project#5]
https://github.com/diegodiazgarciadev/GeoQueries

**Comment by AnaAGG** [comment]
# Proyecto geoqueries 

Hola hola Diego 🙋🏻‍♀️, vamos con el tercer proyectooo

## README

Wow Diego pedazo de readme te has marcado, suuper completo. El único detalle que te puedo decir es:

- Cuando pongas las librerías añadas el link a la documentación oficial. 
  
## Estructura del repo

Suuper, no se te ha pasado ningún archivo temporal, ni el `.env` fuera del `.gitignore`. 

Tienes varias carpetas con los archivos bien organizados. De cara al futuro, en caso de que tuvieras varios jupyters, otra carpeta para guardar los jupyerts numerados 😉

## Sintaxis de código

- Los docstrings lso tienes en algunas funciones y en otras no. Por otro lado, en las que tienes el *docstring* no hay mucha consistencia en el formato. Recuerda, en cada *docstring* tendremos que poner: 
  - Qué es lo que hace la función
  - Qué argumentos recibe la función (args)
  - Qué nos devuelve la función (return)


- Vamos con la función `drop_collections`, la función esta suuper bien, pero como detalle, si te fijas, repites la misma línea de código múltiples veces. ¿Cómo podemos solucionar esto?

    Podemos crear una lista con los nombres de las colecciones que pasaremos como *args* a la función y así es más universal  y luego hacer un *for loop* dentro de la función

    ```python
    para_eliminar = ["vegan_restaurant", "airport", "school", "pubs", "kindergarden", "doggrummer", "venga_restaurant", "starbucks", "startup", "train" ]
    def drop_collections(db, *args):
        for i in args: 
            db.get_collection(i).drop()

    drop_collections (db, *para_eliminar)
    ```
- Vamos con la función `input_cities`, suuper currada esta función pero si te fijas tienes las mismas lineas de código repetida tres veces. 

    ¿Cómo solucionamos esto? Te dejo por aquí unas lineas de código por si te aporta valor, aún así si te queda alguna duda dime y lo vemos 😉

    ```python
    def input_cities(list_sp, list_en):
        geolocator = Nominatim(user_agent="Geomaps")
        city_location1 = []
        city_location2 = []
        city_location3 = []
        d = {}
        
        for i in list(range(1,4)): 
            if len(city_location1) == 0 or len(city_location2) == 0 or len(city_location3) == 0: 

                d["city_name{0}".format(i)] = input("Set the #{0} city: ".format(i))
                print(d["city_name{0}".format(i)])
                try:
                    city_name = {d["city_name{0}".format(i)]}
                    location_geo1 = geolocator.geocode(f'{city_name}')
                    d["city_location{0}".format(i)] = [location_geo1.latitude, location_geo1.longitude]
                    #d["city_name{0}".format(i)] = d["city_name{0}".format(i)].replace(" ", "_")
    #
                    while True:
                        city_lang_input1 = input("select a language for the first city: (en/sp): ")
                        if city_lang_input1.lower() == 'en':
                            city_lang1 = list_en
                            break
                        elif city_lang_input1.lower() == 'sp':
                            city_lang1 = list_sp
                            break
                except:
                    city_location1 = [37.402559152869856, -6.006329402641001]
                    city_name1 = "seville_cartuja"
                    print("default location 1 : ", city_name1)
                    city_lang1 = list_sp

            
        return  city_location1, city_location2, city_location3
    ```
- La función `calculate_marks_mean` esta perfecta, una función que bebe de otras funciones y que calcula las ponderaciones dependiendo del tamaño del equipo. 

    Again, solo como detalle, te recomendaría que hicieras grupos, es decir, que agruparas por el size. 

    Los diseñadores , el contable  y el CEO dentro del tamaño 20; los UX-UI y backend tiene un tamaño de 5 etc. Se podrían usar condicionales: 


## TODOs

En general, trabajazo Diego, un proyecto suuuper completo 😉. Te dejo por aquí algunos puntitos que podrías cambiar, pero como te digo son detalles 

- Homogeneizar los *docstrings* a lo largo de todo el proyecto

- Los links en en el readme cuando haces la lista de las librerias que usas 
- Atomizar el código de algunas funciones. 

Bueno Diego, enhorabuena has hecho un proyecto perfecto  🔝. Solo te di *tips* para ir puliendo el código 💪


![image](https://user-images.githubusercontent.com/75084991/133000871-6ea68db4-3187-423d-a881-5eb06170ff60.png)
