### ISSUE TITLE
[W4-geospatial-data-project] Sergio Garcia Poves

### ISSUE THREAD

**Issue by Sergio-1980** [Ironhack-Data-Madrid-Agosto-2021/W4-geospatial-data-project#6]
Me falta el request y las geoqueries. Hice unas pocas pero sin mucho resultado

https://github.com/Sergio-1980/W4-geospatial-data-project

**Comment by AnaAGG** [comment]
# Proyecto geoqueries

Hola hola Sergio 🙋🏻‍♀️, vamos con el tercer proyectooo

## README

Sergioooo que ha pasado con el readme 😔!! Esta parte del proyecto es la más importante ya que va a ser lo que la gente vea de nuestro trabajo. 

¿Qué es lo que debemos poner en el readme?

1. Objetivo del proyecto
2. En caso de que plantees hipótesis, presentarlas 
3. Que herramientas has usado pra llevar a cabo el proyecto (API, scrappping, etc)
4. Workflow de tu proyecto
5. Resultados si quieres
6. Librerias que has usado
   
## Estructura del repo

Suuper bien estructurado el repo, pero ya sabes que siempre tengo algún detallin que decir: 

- Dentro de la carpeta `data` se te ha pasado un archivo de temporal, el `DS_Store`. Recuerda meterlo en el `gitignore`
  
- Intenta que el jupyter no se llame `cacharreo`, lo ideal es ponerle un nombre algo más "profesional" 
  
- De cara al futuro, cuando tengas más jupyters, lo ideal será que te crees una carpeta nueva que se llame por ejemplo `Notebooks` donde los vayas guardando todos. Además si lo numeras para saber cual es el orden de trabajo te quedaría 🔝🔝

Por el resto todo suuper bien Sergio, buen trabajooooo 😉

## Sintaxis de código

- Vamos con los *docstrings*, genial que lo hayas metido en tus funciones, es esencial para que tus compañeros entiendan que hace la función, que parametros recibe, etc. Como detalle, ¿qué es lo que tenemos que poner en los docstrings?
  - Qué hace la función
  - Qué parámetros recibe
  - Qué nos devuelve la función

    ```python
    # tomando como ejemplo una función tuya
    def generar_json(url, diccionario, token, token2, *args ):
        """
        Esta función genera un json
        Args: 
            url (string): la url a la que vamos a hacer la llama de la API
            diccionario (diccionario): diccionario con las coordenadas de la ciudad objetivo
            token (string): Client_Id de la API de foursquare
            token2 (string): Client_Secret de la API de foursquare
            *args (lista): con los nombres de las queries que queremos sacar
        Returns: 
            Uana lista con una json en su interior con la respuesta de la API
        """
        lst = []
        for i in args:
            parametros = {
                "client_id": token,
                "client_secret": token2,
                "v": "20180323",
                "ll": f"{diccionario['coordinates'][0]}, {diccionario['coordinates'][1]}",
                "query": i,
                "limit": 200
            }
        
            resp = requests.get(url, params=parametros).json()
            lst.append(resp)
        return lst
    ```
- Los prints infinitos de la respuesta de la API Sergio!!!! Importante limitarlos en nuestros jupyters, tienes uno en tu jupyer que ocupa tres cuartas partes !!! 
- Recuerda los *import* siempre al inicio del jupyter! 
- Tienes el código para convertir a geometry tus datos y como meterlos en mongo, lo ideal meterlos en funciones Sergio!! 

Bueno Sergio, quedo la parte de las geoqueries y de decidir que ciudad es la mejor. 

🔴 Si quieres mañana nos podemos sentar los dos y revisamos el proyecto al completo 😉

## TODOs

Poco te puedo decir, sergio, lo que has sacado esta bien pero te queda un pelín  de trabajo: 

- README
- Modularizar el código, sobre todo en la parte final del proyecto
- HAcer las geoqueries

Venga Sergio!!! Seguimos adelante y ya sabes donde estoy para lo que necesitessss, no dudes en preguntarmeeeee ☺️

![image](https://user-images.githubusercontent.com/75084991/132999345-df5368dc-04db-4f98-87a6-0fc6c5464ab6.png)
