### ISSUE TITLE
👎🏼 

### ISSUE THREAD

**Issue by lukesmith194** [Ironhack-Data-Madrid-Agosto-2021/W4-geospatial-data-project#7]
https://github.com/lukesmith194/optimal-offi

**Comment by AnaAGG** [comment]
# Proyecto geoqueries

Hola hola Luke 🙋🏻‍♀️, vamos con el tercer proyectooo

## README

Suuper buen trabajo en el readme Luke 👏🏽. Te dejo por aquí un par de detalles para que quede perfectisimo: 

- En el readme, cuando intentas crear un hipervínculo a la API de foursquare no te quedó bien formateado. ¿Cómo lo podemos hacer?

    ```
    [here](https://api.foursquare.com/v2/venues/explore)
    # el link hay que pasarlo entre paréntesis y sin espacios entre el paréntesis y el corchete
    ```
- De cara al futuro cuando empezemos a trabajar que son más complejos con distintos *steps* (como es el caso de este proyecto) esta bien poner el flujo de trabajo que seguiste. 

    En este caso podemos hacer algo como esto:
    - Lo primero que se hizo fue seleccionar las ciudades
    - Después se hicieron llamadas a la API de foursquare para los siguientes criterios bla bla bla
    - Se metieron todos los datos en una base de datos de mongo, con la siguiente estrucutra bla bla bla
    - Se hicieron geoqueries para sacar la distancia ...
    - Se pondero basado en los criterios anteriormente mencionados

## Estructura del repo

En general esta todo super organizado, pero ya sabes que siempre hay algun detallin que os comento. Vamos allá! Aunque son detalles para que te quede el repo suuper bien organizado:

- Tienes dos carpetas de `Data`, intenta unificarlo para tener una única carpeta

- La carpeta de los notebooks, perfecta! Para rematarlo ya, si numeras los jupyters para saber el orden de trabajo te queda fetén 😉!

- Tienes algunas funciones en los jupyters, se que este no fue tu mejor proyecto, pero intenta para el futuro que cuando hagas una función y te funcione llevarla al `py` dentro de la carpeta src! 

## Sintaxis de código
Vamos con el código!! 

- **API_4sq**

  Las llamadas a la API por separado para ciudad y parémetro esta perfecto, pero como dices, esto hay que meterlo en funciones para evitar todo ese código repetido. 

  Las funciones que tienes para la llamada a la API y la limpieza están bien Luke 💪! En vez de ponerte todo el código aquí con todo el código te comparto un jupyter por slack con la solución para que lo veas paso a paso. 

- **Creating_Geodf**

    Aquí de nuevo te pasó lo mismo que en el ejercicio anterior, tienes el código pero sin funciones... 😔

    - Te dejo por aquí un ejemplo para que te hagas una idea de como lo podriamos hacer: 

        ```python
        # Funcion para sacar el geo point 

        def geodata(df):
            gdf = geopandas.GeoDataFrame(df, geometry=geopandas.points_from_xy(df.latitud,
                                df.longitud))
            gdf.columns=['longitud','latitud','loc']
            gdf['loc']=gdf['loc'].apply(lambda x:shapely.geometry.mapping(x))
            return gdf
        ```
    - Si ya luego te creas otra función para meter los datos en las colecciones de mongo está parte del proyecto te queda perfecta. 
    - Otra cosina a la que le podrías dar una vuelta es que tienes muchos csv, tantos como criterios y ciudades! 

        Esto puede ser un poco dolor, lo que te recomiendo es que te crees un único dataframe, ya sea por:
        - Ciudad: donde tengas toda la información para una ciudad
        - Criterio: donde para cada criterio tengas toda la información de todas las ciudades. 

        Con la funcion que tienes en el primer jupyter eso lo podemos solucionar con lo que tienes al final del primer jupyter: 

        ```python
        for i in query:
        df_dub = all_('https://api.foursquare.com/v2/venues/explore',"53.33925763762811, -6.234433274297044", i)
        dub_.append(df_dub)
        full_dub = pd.concat(dub_)
        ```
- **Geoqueries**

    De nuevo, tu código esta bien, pero las funciones 😔, lo sé, soy muy pesada 🤣
    
## TODOs

Bueno Luke, el proeyecto en general esta bastante bien, la lógica, los pasos que has ido danto... La pena las funciones, pero a partir de ahora nos subimos en el cohetito de las funciones 🚀

Te dejo por aquí un pequeño resumen con los puntos más importantes: 

- Modularizar el código con las funciones
- Workflow de trabajo en el readme
- Cerraría tu prpyecto un mapa de las palmas

Aún con todo suuper buen trabajo Lukeee 💪🔥

![image](https://user-images.githubusercontent.com/75084991/132998015-b3411b86-f2e5-43bb-81fc-b56d5dbbb996.png)
